### ISSUE TITLE
Unable to build "buildRequirements" : ["disallowDeprecations"]

### ISSUE THREAD

**Issue by irakhlin** [carblue/acos5#1]
Hello,

I am not sure if you are still maintaining this project however I had tried to build it as you had mentioned on Ubuntu 15 and now recently on Ubuntu 16 but I get the following errors:
WARNING: A deprecated branch based version specification is used for the dependency                                   sodium. Please use numbered versions instead. Also note that you can still use the                                   dub.selections.json file to override a certain dependency to use a branch instead.
WARNING: A deprecated branch based version specification is used for the dependency                                   opensc. Please use numbered versions instead. Also note that you can still use the                                   dub.selections.json file to override a certain dependency to use a branch instead.
Performing "debug" build using dmd for x86_64.
acos5_64 ~master: building configuration "library"...
../../.dub/packages/opensc-master/source/libopensc/opensc.d(106,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(152,13): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(234,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(235,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(343,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(344,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(371,2): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(372,2): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(374,2): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(375,2): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(388,2): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(449,22): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(481,11): Deprecation: l                                  ibopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(506,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(507,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(508,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(509,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(517,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(518,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(519,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(520,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(537,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/opensc.d(542,6): Deprecation: li                                  bopensc.internal.c_ulong is not visible from module opensc
../../.dub/packages/opensc-master/source/libopensc/pkcs15.d(377,11): Deprecation: l                                  ibopensc.types.c_ulong is not visible from module pkcs15
../../.dub/packages/opensc-master/source/libopensc/pkcs15.d(545,6): Deprecation: li                                  bopensc.types.c_ulong is not visible from module pkcs15
../../.dub/packages/opensc-master/source/libopensc/pkcs15.d(546,6): Deprecation: li                                  bopensc.types.c_ulong is not visible from module pkcs15
../../.dub/packages/opensc-master/source/libopensc/pkcs15.d(546,6): Deprecation: li                                  bopensc.types.c_ulong is not visible from module pkcs15
../../.dub/packages/opensc-master/source/libopensc/pkcs15.d(547,6): Deprecation: li                                  bopensc.types.c_ulong is not visible from module pkcs15

I am able to get it to build if I remove buildRequirements" : ["disallowDeprecations"] from the dub.json file but the resulting binary simple seg faults and does not get picked up by opensc.. Any ideas what could be causing the problem? I am using a newly build version of OpenSC with all the options you had mentioned.

**Comment by carblue** [comment]
Hello,
I'm still maintaining this project, however, on an irregular basis.
In the meantime I did a (clean/no upgrade) install of Kubuntu 16.04 and, following my own advice, ran into the same issues as You did (though issues are not related to Kubuntu version, but probably due to my published libopensc binding package differing from what I have locally within Kubuntu 15.10).
My libopensc binding needs an upgrade anyway, as opensc-0.16.0 got released.
Please stay tuned until I have it working again purely from published sources.

**Comment by carblue** [comment]
If You consider another try, acos5_64 is ready,
All dependencies are updated and properly versioned, acos5_64 is still in master but updated as well.
I personally place buildRequirements" : ["disallowDeprecations"], because I want to succeed compilation only if free of any kind of warnings, and IMHO the warnings about Deprecation: c_ulong is not visible are wrong: Taken seriously they are errors and I wonder why a build succeded at all.
The libacos5_64.so not being picked up by opensc may have severall reasons: Either the so has unresolved load-time dependencies or unresolved symbols or is corrupted in some way (I got least surprises with DMD), or the opensc.conf file isn't setup properly (libacos5_64.so isn't known or not found by opensc or the wrong internal driver acos5 is interfering) or a version mismatch forces the opensc framework to unload libacos5_64.so immediatelly.

Pick up acos5_64-master.zip and extract to an empty location, everything else is explained briefly in the new head of README.md. File config/diff_opensc_conf is cut down to what is essential for the current state of acos5_64. My environment is Kubuntu 16.4 (amd64), all mentioned requirements up-to-date, from repositories, either ubuntu or d-apt [http://d-apt.sourceforge.net/]; opensc from Ubuntu (version 0.15.0) is fine as well. Only when Your opensc has recent version 0.16.0, omit , "FAKE_OPENSC_VERSION" in dub.json.

$ ldd libacos5_64.so 
        linux-vdso.so.1 =>  (0x00007fff37df4000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f0152996000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f015253b000)
        libsodium.so.18 => /usr/lib/x86_64-linux-gnu/libsodium.so.18 (0x00007f01522dc000)
        libopensc.so.3 => /usr/lib/x86_64-linux-gnu/libopensc.so.3 (0x00007f0151f37000)
        libphobos2.so.0.71 => /usr/lib/x86_64-linux-gnu/libphobos2.so.0.71 (0x00007f01516fb000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f01514dd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f01511d4000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0150fcc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0150dc7000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0150bb1000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01507e8000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f01505cd000)
        /lib64/ld-linux-x86-64.so.2 (0x000055832bc87000)

When I run opensc-tool -D  I get ... in the shell and opensc-debug.log:
host@user:~$ opensc-tool -D
Configured card drivers:
  acos5_64         ACS ACOS5-64 (CryptoMate64)
  default          Default driver for unknown cards

ctx.c:726:sc_context_create: ===================================
ctx.c:727:sc_context_create: opensc version: 0.15.0
reader-pcsc.c:668:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=1 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
ctx.c:382:load_dynamic_driver: **successfully loaded card driver 'acos5_64'**
reader-pcsc.c:956:pcsc_detect_readers: called
reader-pcsc.c:970:pcsc_detect_readers: Probing PC/SC readers
reader-pcsc.c:999:pcsc_detect_readers: Establish PC/SC context
reader-pcsc.c:1047:pcsc_detect_readers: Found new PC/SC reader 'ACS CryptoMate64 00 00'
reader-pcsc.c:285:refresh_attributes: ACS CryptoMate64 00 00 check
reader-pcsc.c:309:refresh_attributes: current  state: 0x00000022
reader-pcsc.c:310:refresh_attributes: previous state: 0x00000000
reader-pcsc.c:364:refresh_attributes: card present, changed
reader-pcsc.c:1078:pcsc_detect_readers: Requesting reader features ... 
reader-pcsc.c:1092:pcsc_detect_readers: ACS CryptoMate64 00 00:SCardConnect(SHARED): 0x00000000
reader-pcsc.c:831:detect_reader_features: called
reader-pcsc.c:852:detect_reader_features: Reader feature 12 found
reader-pcsc.c:1122:pcsc_detect_readers: returning with: 0 (Success)
ctx.c:799:sc_release_context: called
reader-pcsc.c:747:pcsc_finish: called
