### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by perkel1** [carblue/acos5#2]
Hello,

I am trying to get the card working on CentOS6/7. I am following the instructions in "readme" to the testing part (opensc-tool -D), but needed line doesn't appear. Debug gives the same output on every system I tried (CentOS6, CentOS7, Ubuntu 16.10).

0x7f9f6f885740 15:32:39.129 [opensc-tool] ctx.c:789:sc_context_create: ===================================
0x7f9f6f885740 15:32:39.129 [opensc-tool] ctx.c:790:sc_context_create: opensc version: 0.16.0
0x7f9f6f885740 15:32:39.129 [opensc-tool] reader-pcsc.c:754:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=1 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
0x7f9f6f885740 15:32:39.133 [opensc-tool] ctx.c:438:load_dynamic_driver: Module acos5_64: cannot load /usr/lib64/libacos5_64.so library: /usr/lib64/libacos5_64.so: undefined symbol: _D9libopensc5types7sc_apdu6__initZ
0x7f9f6f885740 15:32:39.133 [opensc-tool] ctx.c:517:load_card_drivers: Unable to load 'acos5_64'.

I tried using opensc 0.15.2 and 0.16.0 on both CentOS6 and 7 and 0.15.3 on Ubuntu 16.10.
Please tell, if you know what could cause such problem.

**Comment by carblue** [comment]
Hello perkel1,
I'm currently working on 'acos5_64' and a lot of code is waiting for a push. Please keep patient.
The problem You describe:
1. Let's take aside for a while, that I get different opensc source code lines reported (strange: I'm running opensc version: 0.16.0 as well, compiled myself with some patches that don't matter in this context, Kubuntu 16.04 LTS) in my debug file, upon $ opensc-tool -D:
0x7f9c2f694700 03:39:42.053 [opensc-tool] ctx.c:770:sc_context_create: ===================================
0x7f9c2f694700 03:39:42.053 [opensc-tool] ctx.c:771:sc_context_create: opensc version: 0.16.0
0x7f9c2f694700 03:39:42.053 [opensc-tool] reader-pcsc.c:714:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=1 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
0x7f9c2f694700 03:39:42.062 [opensc-tool] ctx.c:441:load_dynamic_driver: successfully loaded card driver 'acos5_64'
0x7f9c2f694700 03:39:42.064 [opensc-tool] reader-pcsc.c:1114:pcsc_detect_readers: called
0x7f9c2f694700 03:39:42.064 [opensc-tool] reader-pcsc.c:1128:pcsc_detect_readers: Probing PC/SC readers
0x7f9c2f694700 03:39:42.064 [opensc-tool] reader-pcsc.c:1156:pcsc_detect_readers: Establish PC/SC context
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:1203:pcsc_detect_readers: Found new PC/SC reader 'ACS CryptoMate64 00 00'
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:303:refresh_attributes: ACS CryptoMate64 00 00 check
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:331:refresh_attributes: current  state: 0x00000022
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:332:refresh_attributes: previous state: 0x00000000
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:389:refresh_attributes: card present, changed
0x7f9c2f694700 03:39:42.065 [opensc-tool] reader-pcsc.c:1235:pcsc_detect_readers: Requesting reader features ... 
0x7f9c2f694700 03:39:42.354 [opensc-tool] reader-pcsc.c:1249:pcsc_detect_readers: ACS CryptoMate64 00 00:SCardConnect(SHARED): 0x00000000
0x7f9c2f694700 03:39:42.354 [opensc-tool] reader-pcsc.c:959:detect_reader_features: called
0x7f9c2f694700 03:39:42.354 [opensc-tool] reader-pcsc.c:980:detect_reader_features: Reader feature 12 found
0x7f9c2f694700 03:39:42.354 [opensc-tool] reader-pcsc.c:900:part10_detect_max_data: get dwMaxAPDUDataSize property returned 65536
0x7f9c2f694700 03:39:42.354 [opensc-tool] reader-pcsc.c:939:part10_get_vendor_product: id_vendor=072f id_product=90db
0x7f9c2f694700 03:39:42.355 [opensc-tool] reader-pcsc.c:1270:pcsc_detect_readers: reader's max-send-size: 65536, max-recv-size: 65536
0x7f9c2f694700 03:39:42.355 [opensc-tool] reader-pcsc.c:1296:pcsc_detect_readers: returning with: 0 (Success)
0x7f9c2f694700 03:39:42.355 [opensc-tool] ctx.c:842:sc_release_context: called
0x7f9c2f694700 03:39:42.355 [opensc-tool] reader-pcsc.c:794:pcsc_finish: called

2. I came across this issue with libopensc.types.sc_apdu.__init as well some time ago (and didn't push since ;-) ). It's about a D structure initialization detail which seems to have changed since some DMD version in the meantime.
Meanwhile I included a "--no-undefined" in "lflags-dmd"...

But the short story is: I should hurry to get the current code I'm running "cleaned" for a push to Github and the problem will be gone probably. Again, please keep patient.
From the remaining debug content I conclude that compiling seemed to be no problem in general and the opensc.conf is configured such that opensc can find and wants to load libacos5_64.so. I recommend to stick with the latest opensc version 0.16.0.
Cheers, Carblue

**Comment by andrewlukoshko** [comment]
With new version there are another errors:
```
Target '/home/a.lukoshko/acos5_64/.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/libacos5_64.so' doesn't exist, need rebuild.
acos5_64 ~master: building configuration "library"...
Using pkg-config to resolve library flags for libssl, libcrypto.
Using direct -l... flags for :libopensc.so.
dmd -defaultlib=libphobos2.so -c -of.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o -release -inline -O -w -de -version=ENABLE_SM -version=ENABLE_ACOS5_64_UI -version=Have_acos5_64 -version=Have_openssl -version=Have_opensc -Isource/ -I../.dub/packages/opensc-0.15.5/opensc/source/ -I../.dub/packages/openssl-1.1.5_1.0.1g/openssl source/acos5_64.d -fPIC -vcolumns
source/acos5_64.d(270,23): Error: cannot implicitly convert expression (& acos5_64_decipher) of type extern (C) int function(sc_card* card, const(ubyte)* in_, ulong in_len, ubyte* out_, ulong out_len) to extern (C) int function(sc_card* card, const(ubyte)* in_, const(ulong) in_len, ubyte* out_, const(ulong) out_len)
source/acos5_64.d(271,23): Error: cannot implicitly convert expression (& acos5_64_compute_signature) of type extern (C) int function(sc_card* card, const(ubyte)* in_, ulong in_len, ubyte* out_, ulong out_len) to extern (C) int function(sc_card* card, const(ubyte)* in_, const(ulong) in_len, ubyte* out_, const(ulong) out_len)
source/acos5_64.d(1392,2): Error: undefined identifier 'bytes2apdu'
source/acos5_64.d(1367,23): Error: function acos5_64.acos5_64_logout no return exp; or assert(0); at end of function
source/acos5_64.d(2321,2): Error: undefined identifier 'bytes2apdu'
source/acos5_64.d(2066,23): Error: function acos5_64.acos5_64_compute_signature no return exp; or assert(0); at end of function
FAIL .dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/ acos5_64 dynamicLibrary
dmd failed with exit code 1.
```

**Comment by andrewlukoshko** [comment]
And BTW there is no "deimos" configuration in opensc, I had to delete this:
```
	"subConfigurations": {
		"opensc": "deimos"
	},
```
from dub.json

**Comment by carblue** [comment]
I missed updating my package opensc. It's version 0.15.6 now and should do it for updated acos5_64's dub.json.
Be aware, that I dropped support for OpenSC's libopensc.so versions other than the latest, currently 0.16.0 from June 2016.

**Comment by andrewlukoshko** [comment]
Now it fails with this:
```
dmd -defaultlib=libphobos2.so -c -of.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o -release -inline -O -w -de -version=ENABLE_SM -version=ENABLE_ACOS5_64_UI -version=Have_acos5_64 -version=Have_openssl -version=Have_opensc -Isource/ -I../.dub/packages/opensc-0.15.6/opensc/source/ -I../.dub/packages/openssl-1.1.5_1.0.1g/openssl source/acos5_64.d -fPIC -vcolumns
Linking...
dmd -of.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/libacos5_64.so .dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o -L--no-as-needed -L--no-undefined -L--strip-all -L--version-script=lib/libacos5_64.ver -L-lssl -L-lcrypto -L-l:libopensc.so -shared -defaultlib=libphobos2.so
.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o: In function `acos5_64_match_card':
source/acos5_64.d:(.text.acos5_64_match_card+0x68): undefined reference to `_sc_match_atr'
.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o: In function `acos5_64_init':
source/acos5_64.d:(.text.acos5_64_init+0x175): undefined reference to `_sc_card_add_rsa_alg'
.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o: In function `acos5_64_decipher':
source/acos5_64.d:(.text.acos5_64_decipher+0x66d): undefined reference to `sc_pkcs1_strip_02_padding'
source/acos5_64.d:(.text.acos5_64_decipher+0x755): undefined reference to `sc_pkcs1_strip_02_padding'
.dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/acos5_64.o: In function `acos5_64_compute_signature':
source/acos5_64.d:(.text.acos5_64_compute_signature+0x3c0): undefined reference to `sc_pkcs1_strip_01_padding'
collect2: ld returned 1 exit status
Error: linker exited with status 1
FAIL .dub/build/library-release-linux.posix-x86_64-dmd_2072-3977D20CD437FB3FBE819868758AAEF3/ acos5_64 dynamicLibrary
dmd failed with exit code 1.
```

OpenSC is 0.16.0:
```
OpenSC 0.16.0 [gcc  4.4.7 20120313 (CentOS 4.4.7-17)]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
```

DMD is latest:
```
DMD64 D Compiler v2.072.2
Copyright (c) 1999-2016 by Digital Mars written by Walter Bright
```

**Comment by andrewlukoshko** [comment]
I know you asked not to do this, but... :)
With FAKE_OPENSC_VERSION I've successfully built module and it's now loading:
```
Configured card drivers:
  acos5_64         ACS ACOS5-64 (CryptoMate64)
  default          Default driver for unknown cards
```
Thank you!

**Comment by carblue** [comment]
Hi Andrew,
maybe this comment doesn't matter as You successfully built finally, BUT there was something strange going on in Your installation and be aware, that - when You define FAKE_OPENSC_VERSION - then You are in the world/API of OpenSC version 0.15.0 and what can be called from that libopensc.so, thus You have no RSA private key operations sign and decrypt support from the driver but from opensc which doesn't work for acos at least for keys>2048 bit, if at all IIRC (sign and decrypt support from the driver relies on sc_pkcs1_strip_0?_padding functions, which aren't implemented/duplicated by me; the reason why acos5_64 doesn't support 0.15.0 well/no fun !):
The undefined references are related to exactly those symbols/functions that are missing exports in 0.15.0 but present in 0.16.0 OpenSC's libopensc.so.
Thus You have installed version 0.16.0 and don't actually use it for this driver, but presumably a libopensc.so from version 0.15.0 is also still present and somehow gets preference over the newly installed one. I did an uninstall of my distribution's/Kubuntu's OpenSC related installations (v0.15.0) and manually installed version 0.16.0, replacing sudo make install by sudo checkinstall, thus I can easily undo the installation again using sudo dpkg -r opensc_name_given_during_checkinstall, once Kubuntu supports the latest OpenSC release or for testing purpose and don't get into this mixed .so problem.

By the way, I would like to know, if Your card/token is filled with the necessary files for PKCS#15 compliance; in case You don't know what I'm talking about: I uploaded to acos5_64 dir info a file pkcs15fs.pdf, that shows an example. Relevant files for sign/decipher (of which these 2 must be present with exactly the File IDs given in the pdf: MF, DIR), PKCS#15 (with acos it's probably 4100), ODF (probably 5031), TokenInfo (probably 5032), AODF (Pin information file), PrKDF (RSA priv. key information file), PuKDF (RSA public key information file), PrKey (1. RSA priv. key file, probably 41F1), PuKey (1. RSA public key file, probably 4131).
The reason why I*m asking is, my token, virgin from supplier mid 2014 + initialized with acos client kit software (setting up user pin + SO pin)+loading a certificate refering to one of tokens RSA pub. keys to the token had an empty ODF, thus opensc couldn't know about any objects on the token, didn't know about pins despite stored on token, didn't know about RSA keys despite 10 pairs of key files got preallocated already and many more empty files, not knowing what they are used for, and EEPROM's free space was nearly exhausted, before I began storing any new file myself.
It turned out, that the proprietary driver I have, somehow operates in it's own way on the token, bypassing PKCS#15.
I would like to know, if the file structure/content situation changed in the meantime or if You are doing corrections manually, in order to estimate the importance/priority of acos5_64 driver to be able to initialize the token.
The code for token-initialization is ready essentially, but I withhold it because I'm still changing details about what shall be written to a card/token and there are still details ref. opensc access control and Secure Messaging and integration within OpenSC code flow, that I don't yet fully understand. Also, despite my mucky client kit, I think it's advisable to be compatible with that and install what is essential for that too (which needs testing, much time for testing). It's about to find the right balance of security and user's flexibility. A lot of things must be fixed/known in advance, and won't be changeable until a new token-initialization is done, loosing all card content.
With e.g. command opensc-tool -f  You can inspect the file structure of Your card/token.

Your info will be very much appreciated. Thanks in advance! And in the unlikely case You meet and get into a conversation with Mr.E. Snowden, You could tell him, that my spending a lot of spare time on this driver is due to his attitude as well.

As a usage example and continuous test of driver's RSA signing, I switched my repo's remote URL from HTTPS to SSH and execute git push authorized with one of my keys (no nasty password entry for github account any more).

The following is an excerpt of what is on my token as an example (having run my token-initialization function; contents are still not perfect; erase[NEVR] is wrong in some places, TokenInfo supported algos must probably be changed and ODF doesn't include an entry for SKDF. Sec# means Security condition must be fullfilled as detailed in contents of a record, referenced by Sec#-1 in 3f000003 or 3f0041004103.

user@host:~$ opensc-tool -f
Using reader with a card: ACS CryptoMate64 00 00
3f00 type: DF, size: 0
select[NONE] lock[NONE] delete[NONE] create[NONE] rehab[NONE] inval[NONE] list[NONE] 

  3f000001 type: iEF, ef structure: linear-fixed, size: 21
  read[NEVR] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#1] inval[Sec#1] 

Record 0
  3f000002 type: iEF, ef structure: linear-variable, size: 148
  read[NEVR] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#1] inval[Sec#1] 
despite having set never read, opensc-tool does read because I forgot file activation
Record 0
00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000020: 00 00 00 00 00                                  .....
...
Record 3  all bytes zero as well
  3f000003 type: iEF, ef structure: linear-variable, size: 48
  read[Sec#1] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#1] inval[Sec#1] 

Record 0
  3f002f00 type: wEF, ef structure: transparent, size: 33
  read[NONE] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#1] inval[Sec#1] 

00000000: 61 1F 4F 10 41 43 4F 53 50 4B 43 53 2D 31 35 76 a.O.ACOSPKCS-15v
00000010: 31 2E 30 30 50 05 65 43 65 72 74 51 04 3F 00 41 1.00P.eCertQ.?.A
00000020: 00                                              .
  3f004100 [ACOSPKCS-15v1.00] type: DF, size: 0
  select[NONE] lock[NEVR] delete[Sec#3] create[Sec#3] rehab[Sec#3] inval[Sec#3] list[NONE] 

    3f0041004129 type: wEF, ef structure: linear-fixed, size: 40
    read[NONE] update[NONE] erase[NONE] write[NONE] rehab[NONE] inval[NONE] 

Record 0
00000000: 00 00 00 00 +12 more bytes 
00000010: 4 bytes                                     ....
Record 1
00000000: 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 ................
00000010: 00 00 00 00                                     ....
    3f0041004101 type: iEF, ef structure: linear-fixed, size: 21
    read[NEVR] update[Sec#3] erase[NEVR] write[Sec#3] rehab[Sec#3] inval[Sec#3] 

Record 0
    3f0041004102 type: iEF, ef structure: linear-variable, size: 407
    read[NEVR] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#3] inval[Sec#3] 

Record 0
...
Record 10
    3f0041004103 type: iEF, ef structure: linear-variable, size: 240
    read[Sec#1] update[Sec#3] erase[NEVR] write[Sec#3] rehab[Sec#3] inval[Sec#3] 

Record 0
...
Record 4
    3f0041005032 type: wEF, ef structure: transparent, size: 192
    read[NONE] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#3] inval[Sec#3] 

00000000: 30 81 B0 02 01 01 04 06 C0 C6 40 68 81 C7 0C 1A 0.........@h....
00000010: 41 64 76 61 6E 63 65 64 20 43 61 72 64 20 53 79 Advanced Card Sy
00000020: 73 74 65 6D 73 20 4C 74 64 2E A0 1B 0C 19 43 72 stems Ltd.....Cr
00000030: 79 70 74 6F 4D 61 74 65 36 34 5F 43 30 43 36 34 yptoMate64_C0C64
00000040: 30 36 38 38 31 43 37 03 02 05 20 A2 66 30 0F 02 06881C7... .f0..
00000050: 01 01 02 01 00 05 00 03 02 00 01 02 01 10 30 0F ..............0.
00000060: 02 01 02 02 01 01 05 00 03 02 00 5C 02 01 10 30 ...........\...0
00000070: 0F 02 01 03 02 01 06 05 00 03 02 00 50 02 01 10 ............P...
00000080: 30 0F 02 01 04 02 01 40 05 00 03 02 00 50 02 01 0......@.....P..
00000090: 10 30 0F 02 01 05 02 01 03 05 00 03 02 00 40 02 .0............@.
000000A0: 01 10 30 0F 02 01 06 02 01 03 05 00 03 02 00 04 ..0.............
000000B0: 02 01 13 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
    3f0041005031 type: wEF, ef structure: transparent, size: 80
    read[NONE] update[Sec#3] erase[NEVR] write[Sec#3] rehab[Sec#3] inval[Sec#3] 

00000000: A8 0A 30 08 04 06 3F 00 41 00 12 34 A0 0A 30 08 ..0...?.A..4..0.
00000010: 04 06 3F 00 41 00 12 35 A1 0A 30 08 04 06 3F 00 ..?.A..5..0...?.
00000020: 41 00 12 36 A4 0A 30 08 04 06 3F 00 41 00 12 37 A..6..0...?.A..7
00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
...
The next is AODF:
    3f0041001234 type: wEF, ef structure: transparent, size: 128
    read[NONE] update[Sec#3] erase[NEVR] write[Sec#3] rehab[Sec#3] inval[Sec#3] 

00000000: 30 34 30 0A 0C 04 55 73 65 72 03 02 06 40 30 03 040...User...@0.
00000010: 04 01 01 A1 21 30 1F 03 02 02 CC 0A 01 01 02 01 ....!0..........
00000020: 04 02 01 08 02 01 08 80 02 00 01 04 01 FF 30 06 ..............0.
00000030: 04 04 3F 00 41 00 00 00 00 00 00 00 00 00 00 00 ..?.A...........
00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
which is ASN.1 decoded as (there is currently only 1 PIN, labeled User made available to OpenSC):
SEQUENCE (3 elem)
  SEQUENCE (2 elem)
    UTF8String User
    BIT STRING (2 bit) 01
  SEQUENCE (1 elem)
    OCTET STRING (1 byte) 01
  [1]  (1 elem)
    SEQUENCE (8 elem)
      BIT STRING (6 bit) 110011
      ENUMERATED
      INTEGER 4
      INTEGER 8
      INTEGER 8
      [0] (2 byte) 0001
      OCTET STRING (1 byte) FF
      SEQUENCE (1 elem)
        OCTET STRING (4 byte) 3F004100

The next is PrKDF:
    3f0041001235 type: wEF, ef structure: transparent, size: 512
    read[NONE] update[Sec#1] erase[NEVR] write[Sec#1] rehab[Sec#3] inval[Sec#3] 

00000000: 30 3C 30 0F 0C 06 43 41 72 6F 6F 74 03 02 06 C0 0<0...CAroot....
00000010: 04 01 01 30 17 04 01 01 03 03 06 20 40 03 02 03 ...0....... @...
00000020: B8 02 01 01 A1 06 02 01 02 02 01 05 A1 10 30 0E ..............0.
00000030: 30 08 04 06 3F 00 41 00 41 F1 02 02 10 00 30 43 0...?.A.A.....0C
00000040: 30 10 0C 07 43 41 69 6E 74 65 72 03 02 06 C0 04 0...CAinter.....
00000050: 01 01 30 1D 04 01 02 03 03 06 20 40 03 02 03 B8 ..0....... @....
00000060: 02 01 02 A1 0C 02 01 02 02 01 03 02 01 04 02 01 ................
00000070: 05 A1 10 30 0E 30 08 04 06 3F 00 41 00 41 F2 02 ...0.0...?.A.A..
00000080: 02 10 00 30 3C 30 10 0C 07 44 65 63 72 79 70 74 ...0<0...Decrypt
00000090: 03 02 06 C0 04 01 01 30 16 04 01 03 03 02 02 44 .......0.......D
000000A0: 03 02 03 B8 02 01 03 A1 06 02 01 02 02 01 06 A1 ................
000000B0: 10 30 0E 30 08 04 06 3F 00 41 00 41 F3 02 02 10 .0.0...?.A.A....
000000C0: 00 30 44 30 14 0C 0B 44 65 63 72 79 70 74 53 69 .0D0...DecryptSi
000000D0: 67 6E 03 02 06 C0 04 01 01 30 1A 04 01 04 03 03 gn.......0......
000000E0: 06 60 40 03 02 03 B8 02 01 04 A1 09 02 01 02 02 .`@.............
000000F0: 01 05 02 01 06 A1 10 30 0E 30 08 04 06 3F 00 41 .......0.0...?.A
00000100: 00 41 F4 02 02 10 00 30 45 30 15 0C 0C 44 65 63 .A.....0E0...Dec
00000110: 72 79 70 74 53 69 67 6E 32 03 02 06 C0 04 01 01 ryptSign2.......
00000120: 30 1A 04 01 05 03 03 06 60 40 03 02 03 B8 02 01 0.......`@......
00000130: 05 A1 09 02 01 02 02 01 05 02 01 06 A1 10 30 0E ..............0.
00000140: 30 08 04 06 3F 00 41 00 41 F5 02 02 07 00 00 00 0...?.A.A.......
00000150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000180: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00000190: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001B0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001C0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001E0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
000001F0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................

which's 1. entry is ASN.1 decoded as (it refers to my 1. PrKey RSA 4096 bit):
SEQUENCE (3 elem)
  SEQUENCE (3 elem)
    UTF8String CAroot
    BIT STRING (2 bit) 11
    OCTET STRING (1 byte) 01
  SEQUENCE (5 elem)
    OCTET STRING (1 byte) 01
    BIT STRING (10 bit) 0010000001
    BIT STRING (5 bit) 10111
    INTEGER 1
    [1] (2 elem)
      INTEGER 2
      INTEGER 5
  [1] (1 elem)
    SEQUENCE (2 elem)
      SEQUENCE (1 elem)
        OCTET STRING (6 byte) 3F00410041F1
      INTEGER 4096

**Comment by andrewlukoshko** [comment]
Hi!
I was able to build driver correctly (without FAKE_OPENSC_VERSION) after rebuild of OpenSC 0.16.0 with missing functions:
```
_sc_card_add_rsa_alg
_sc_match_atr
sc_pkcs1_strip_01_padding
sc_pkcs1_strip_02_padding
```
added to **src/libopensc/libopensc.exports**

Now everything looks fine, at least with building.
Working with card is in progress.
