### ISSUE TITLE
CKR_USER_PIN_NOT_INITIALIZED

### ISSUE THREAD

**Issue by johughes99** [carblue/acos5#6]
I initiliased and set the SO and user's PIN using the CS Windows Certifciate Management Utility.  That worked fine.

Then moved onto Ubuntu system  On the first C_Logon call as the CK_USER I got back CKR_USER_PIN_NOT_INITIALIZED

Using either pkcs15-tool or pkcs11-tool how should i reinit the token and set the SO and user PINS - as something obviosly issnt carrying over from the MS stuff

**Comment by carblue** [comment]
You used an ACS tool for card initialization?
The most polite I can tell about that is: I'm not a fan since I used the CryptoMate64 Client Kit. That was so frustrating, I'll never buy any of that software again and it's for Windows only, and it's not PKCS#15 compliant (presumably the reason for Your current problem: no EF.ODF content, no EF.AODF content with PIN infos and so on, but some proprietary things done, that ACS will never disclose).  There is a standard, PKCS#15, dedicated exactly to solve these things in a vendor-independant way, but ACS doesn't seem to care.
There is more in https://github.com/carblue/acos5/blob/master/info/card_initialization/README.md
I don't provide card initialization support via OpenSC tools, but by the `scriptor` scripts provided. I believe, that it's easier this way and more powerful. If You understand the syntax of the commands - I hope the comments inside `card_initialization.scriptor` help with that, or You have the reference manual - then You can set e.g. individual pins/sym. algo keys already in the script.

Just for fun with Your current card content: Did You issue opensc-tool --list-files ? are You happy with that, know what the files are for, and know, that there is almost no EEPROM space left for anything else. Are the existing RSA files empty or need to be populated and does the ACS tool allow to do that. Perhaps that got better in the meantime.

One thing that I haven't yet tested and probably won't work currently is uploading certificate(s) with my driver. I think that will be finished and working this month.

**Comment by johughes99** [comment]
Yup - unfortunately I bought the AC client kit.

and Im not a fan of ACS - given the many emails that  have sent to them and not once have they ever got back to. me.

The reasons if doing this is because Im undertaling a large peiece of work looking at PKCS#11 conformamce. across many types of tokens (many of which are not opensc based)  Cryptomate is one of the last tokens I'm looking at.

I will look at the readme and get if I have any issues

I tred pkcs15-init - but kept getting back "Security status no satisfied"

**Comment by johughes99** [comment]
i have downloaded and built pcsc-tools
 - and pcsc-scan is running nicely.

But how do I run card_initialization.scriptor

Is it as simple as typing 

- scriptor card_initialization.scriptor

on the command line - with suitable edits of the script file of course!

**Comment by carblue** [comment]
"Security status no satisfied"
That's probably from OpenSC/my driver trying to read the Security environment file (which has information how to verify a pin etc.).
ACS has built in a catch-22.

Just
$ ./card_initialization.scriptor

**Comment by johughes99** [comment]
Brilliant - that seems to have sorted it out.

If I find anything unusal -that does not appear to be a generic OpenSC issue - I will post it here

**Comment by carblue** [comment]
You are welcome!
If You need any docs, just ask via my file's Cargo.toml adress.

**Comment by johughes99** [comment]
will do
